component 0, try 0:
max overfill = 1, num max overfills = 22
max overfill = 1, num max overfills = 6
max overfill = 1, num max overfills = 6
Embedding found. Minimizing chains...
max chain size = 1, num max chains = 6, qubits used = 6
max chain size = 1, num max chains = 6, qubits used = 6
max chain size = 1, num max chains = 6, qubits used = 6
max chain size = 1, num max chains = 6, qubits used = 6
[[887], [881], [882], [886], [880], [885]]
