component 0, try 0:
max overfill = 1, num max overfills = 14
max overfill = 1, num max overfills = 10
max overfill = 1, num max overfills = 8
Embedding found. Minimizing chains...
max chain size = 1, num max chains = 8, qubits used = 8
max chain size = 1, num max chains = 8, qubits used = 8
max chain size = 1, num max chains = 8, qubits used = 8
max chain size = 1, num max chains = 8, qubits used = 8
[[951], [944], [947], [948], [945], [949], [946], [950]]
