component 0, try 0:
max overfill = 1, num max overfills = 46
max overfill = 1, num max overfills = 14
max overfill = 1, num max overfills = 14
Embedding found. Minimizing chains...
max chain size = 2, num max chains = 4, qubits used = 14
max chain size = 2, num max chains = 4, qubits used = 14
max chain size = 2, num max chains = 3, qubits used = 13
max chain size = 2, num max chains = 3, qubits used = 13
[[254], [250, 252], [251], [253], [248], [255], [262], [259, 260], [246], [240, 244]]
